#any yaml file to apply in kubernetes kubectl apply -f nameoftheyamlfile/if you want to delete it kubectl delete -f nameof the yamlfile
#any yaml will run from top to bottom and left to right. 
apiVersion: apps/v1 #so we invoke an api apps/v1
kind: Deployment #in apps/v1 api we are telling him to create a deployment
metadata: #using metadata i am giving a name to the deployment
  name: app2-nginx-deployment #name of the deployment
  labels:
    app: app2-nginx
spec:
  replicas: 1
  selector: #slector map{key.value}
    matchLabels: #matchexpression
      app: app2-nginx #{key.value}
  #block related to pod creation
  template:
    metadata:
      labels:
        app: app2-nginx
    spec:
      containers:
      - name: app2-nginx 
        image: stacksimplify/kube-nginxapp2:1.0.0
        ports:
          - containerPort: 80