apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual #how i am going to map the pv with pvc
  resources:
    requests:
      storage: 10G